### ISSUE TITLE
Error Unknown function: l#log

### ISSUE THREAD

**Issue by Qiguang** [still-dreaming-1/vim-project-tags#3]
Hello, I used vundle to install vim-project-tags and vim-elhiv. but it reported errors after installing them and every time when I open vim.
it says error detected while processing function project_tags#add_built_in_language_support[1]..project_tags#add_language: E117: Unknown function: l#log. I am not familiar with vim script. I just browsed *.vim files under these 2 projects. but I cannot find the function l#log. so is this a bug or I did some thing wrong? BTW, I used cygwin.

**Comment by still-dreaming-1** [comment]
I have not tried it in cygwin yet. I will try it out.

**Comment by still-dreaming-1** [comment]
I think I know what is wrong. I still have not tested this on cygwin, but I reproduced the error. There is one one more install step in addition to using vundle to install it. You need to add this line to your .vimrc:

`source $HOME/.vim/bundle/vim-elhiv/elhiv.vim`

I realize this is highly unusual, but it enables a nicer code style I used in elhiv. Let me know if that helps.

**Comment by Qiguang** [comment]
Yes, it is helpful. But as you said, it is indeed unusual. Anyway, it works now, thanks.
